# Generated by Django 5.0.6 on 2024-07-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-date_posted',)},
        ),
    ]
