# Generated by Django 5.0.6 on 2024-07-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('date_posted',), 'verbose_name_plural': 'Posts'},
        ),
    ]
