# Generated by Django 5.0.6 on 2024-07-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=60)),
                ('tavsilot', models.TextField()),
                ('muallif', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ('muallif',),
            },
        ),
    ]
